### ISSUE TITLE
UX: only accepting compressed Secp256k1 pubkey

### ISSUE THREAD

**Issue by nooomski** [samepant/cosmoshub-legacy-multisig#3]
I've been trying to test this tool out, but was unable to without putting some effort into converting my address to compressed Secp256k1.

In order to provide a smooth user experience for users on all expertise levels, it would be great if this tool would accept addresses as directly copied from wallets like Keplr. Are you able to implement a check, so that the tool auto-detects the pubkey type and converts where necessary?

**Comment by webmaster128** [comment]
An address is not sufficient in many situations as you need the pubkey to construct the multisig pubkey. Sometimes you can use an address to query the corresponding pubkey from the chain. But this is not trivial to implement and only works if the address was used before.

I think the more sustainable approach would be to build wallets that make the pubkey accessible by the user.

**Comment by nooomski** [comment]
Yeah, getting pubkey from wallets would be a great feature as well. For now this has already been addressed and the tool now accepts both pubkey & address. So will close this issue unless there's reason to discuss further.
