### ISSUE TITLE
Gas display is incorrect

### ISSUE THREAD

**Issue by greg-szabo** [samepant/cosmoshub-legacy-multisig#5]
This is a small UX change:

The display of Gas (example: https://cosmoshub-legacy-multisig.vercel.app/multi/cosmos16k579jk6yt2cwmqx9dz5xvq9fug2tekv6g34pl/transaction/317278883132998223)

shows that it is in uatom, which is incorrect. The gas has no denomination, it's just a counter.

The fee HAS denomination and if there is any in the transaction, it should be displayed. (Or 0uatom if there is none.)

**Comment by webmaster128** [comment]
#8 should address the issue described here
